### ISSUE TITLE
NMS: Real-time search

### ISSUE THREAD

**Issue by KristianLyng** [tech-server/tgmanage#100]
Update search matching as time ticks (specially useful during replay)

**Comment by jallakim** [comment]
Issue nummer 100. Da blir det bløtkake?!

**Comment by jallakim** [comment]
This issue was moved to tech-server/tgnms#1

**Comment by jallakim** [comment]
Kan bruke https://github-issue-mover.appspot.com/ om du ikke vil flytte manuelt. Skulle bare teste (-:

**Comment by KristianLyng** [comment]
This issue was moved to tech-server/tgnms#2
