### ISSUE TITLE
FAP: subnet-regning

### ISSUE THREAD

**Issue by ldev** [tech-server/tgmanage#19]
Gå over fra "slette siste oktett, legge til .1/:1" til å regne ut første brukbare adresse i subnettet, og sette den som default gateway.

Eks: IPv4 mgmt: 10.0.4.5/16 = 10.0.0.1 som IPv4 GW

Gjelder både IPv4/IPv6

**Comment by jallakim** [comment]
@ldev Følges opp til TG17?

**Comment by ldev** [comment]
Lukkes ettersom FAP blir spist av ISC-DHCP og Gondul
