### ISSUE TITLE
FAP: Logging

### ISSUE THREAD

**Issue by ldev** [tech-server/tgmanage#20]
Logging til egen logging-mappe, og samkjøre formatene

fap/logs/dhcpd.log
fap/logs/httpd.log

Format:
[< timestamp >] [< daemon >] [< client identifier (MAC/IP) >] [< log message >]

Vurdere: rullering på logger. dhcpd.< n >.log, httpd.< n >.log

**Comment by jallakim** [comment]
@ldev Følges opp til TG17?

**Comment by ldev** [comment]
Lukkes ettersom FAP blir spist av ISC-DHCP og Gondul
