### ISSUE TITLE
NMS2: Add moving of switches

### ISSUE THREAD

**Issue by KristianLyng** [tech-server/tgmanage#24]
- [ ] Basic movement of switches
- [ ] Resizing of switches
- [ ] Editing switch-information in general
- [ ] Authentication (don't let Tech:Net mess it up11!1)

**Comment by KristianLyng** [comment]
For auth: Just use the username from basic-auth

**Comment by Atriusftw** [comment]
> Authentication (don't let Tech:Net mess it up11!1)

o_O
