### ISSUE TITLE
NMS: Teste en del i iceweasel/firefox

### ISSUE THREAD

**Issue by KristianLyng** [tech-server/tgmanage#35]

**Comment by magnuskiro** [comment]
Keyboard shortcuts broken in Firefox.

**Comment by magnuskiro** [comment]
k and l hotkeys broken.
Also h is really slow.

**Comment by jallakim** [comment]
Oppgradert til "bug" siden det ikke virker i FF.

**Comment by KristianLyng** [comment]
This issue was moved to tech-server/tgnms#10
