### ISSUE TITLE
NMS: Bedre SNMP-browser

### ISSUE THREAD

**Issue by KristianLyng** [tech-server/tgmanage#37]
- [ ] Egen boks
- [ ] Ikke en enorm dump i plain-text
- [ ] Live-oppdatering? Sparklines?

**Comment by jallakim** [comment]
Dette er vel fikset i stor grad? Du får se om den skal lukkes eller endres, @KristianLyng.

**Comment by KristianLyng** [comment]
This issue was moved to tech-server/tgnms#8
