### ISSUE TITLE
NMS: Scrubbe tidsreiser (igjen)

### ISSUE THREAD

**Issue by KristianLyng** [tech-server/tgmanage#49]
Kjernefunksjonaliteten er endret/flyttet litt, så må oppdateres. Kan bli litt mer utfordrende fordi vi må eksplisitt be om to datapunkter. Nye modellen er bedre, men krever altså litt mer logikk på tidsreiser.

Setter dette til mandag, så vi kan replaye åpningen.

**Comment by jallakim** [comment]
@KristianLyng. Done?

**Comment by jallakim** [comment]
Broken grunnet schemabytte.

**Comment by KristianLyng** [comment]
Har basics i orden igjen nå, men er en del små-plukk.

Alt burde konverteres til ren epoch, bortsett fra ved visning. Det kan faktisk gi mening å vise UTC-tid, for hvordan ellers skal vi forholde oss til at klokka hopper en time? Om du ber om data 02:30 når 02:30 ikke finnes?

**Comment by KristianLyng** [comment]
This issue was moved to tech-server/tgnms#11
