### ISSUE TITLE
NMS: Lag ny svitsj

### ISSUE THREAD

**Issue by KristianLyng** [tech-server/tgmanage#50]
Err, har glemt dette!

Dette bør kunne rappes fra editeringen, siden det er 100% kliss likt, du bare setter et nytt sysname.

Alternativet er å bare be om et navn også hoppe rett til edit.

**Comment by niccofyren** [comment]
Basisfunksjonalitet på plass. Må bygges om i sammenheng med ny nmsInfoBox struktur.
