### ISSUE TITLE
NMS: "Hvilken rad er jeg på"

### ISSUE THREAD

**Issue by KristianLyng** [tech-server/tgmanage#51]
Både IPv4- og IPv6-støtte.

Må hente ARP-tabell, ND-tabell, samt MAC-adresse-tabell fra alle rutere/switcher, slik at switch + switchport kan finnes ut basert på klienten sin IP-adresse.

ARP/ND/MAC-tabell gir også fordel at man kan lage statistikk på «antall IPv4 vs. IPv6-klienter», samt f.eks. «antall unike klienter» (basert på MAC-adresse). Sistnevnte kan kanskje delvis gjøres vha. DHCP-tail-greia, men.

**Comment by KristianLyng** [comment]
Mulig dette må hentes fra X-Forwarded-For

**Comment by KristianLyng** [comment]
Dette kan glatt gjøres 100% serverside, uten javascript.

**Comment by magnuskiro** [comment]
completed with 4dffc5e5431c83595f2bd102f120ad6def011d22

**Comment by jallakim** [comment]
Gjenåpnes grunnet at det skal implementeres med switchport-støtte. Dette innebærer at ARP-tabell, ND-tabell (IPv6-naboskap), samt MAC-adresse-tabell må hentes inn fra alle rutere/switcher.

**Comment by jallakim** [comment]
Pga. sensitivitet så må logikken implementeres server-side på public API-et (dvs, bruke IPv4 og/eller IPv6-adressen til klienten som sender requesten, slik at kun informasjon om klienten som besøker kan brukes). På private-API-et så kan man få lov til å gi et parameter (IPv4/IPv6), slik at man kan "søke" på en IP for å finne ut hvor den er.

**Comment by KristianLyng** [comment]
This issue was moved to tech-server/tgnms#16
