### ISSUE TITLE
NMS: Klikk en plass utenfor containeren for å komme tilbake til "root" view

### ISSUE THREAD

**Issue by skandix** [tech-server/tgmanage#56]
Legge til slik at når man går inn på noen av elementene som ligger i meny listen f.eks "Keyboard Shortcuts" at når man så vil komme seg ut, at man kan bare trykke på en plass som ligger utenfor "containeren/boksen" for å så komme seg tilbake til "root" view.

**Comment by niccofyren** [comment]
Har lagt opp en foreløpig trigger som skjuler infoboks ved klikk på tomt kartområde. Når øvrige dialogbokser flyttes over til nmsInfoBoks-strukturen vil fiksen gjelde "alle" dialogbokser. Samme gjelder "esc" for lukking av dialog.

**Comment by jallakim** [comment]
Da blir resten av denne tasken å fikse «øvrige dialogbokser».

**Comment by KristianLyng** [comment]
This issue was moved to tech-server/tgnms#14
