### ISSUE TITLE
UEFI support for PXE

### ISSUE THREAD

**Issue by norrs** [tech-server/tgmanage#6]
Use "arch" to provide correct bootfile. 

See for example: https://wiki.kubuntu.org/UEFI/SecureBoot-PXE-IPv6 
& https://access.redhat.com/site/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Installation_Guide/s1-netboot-pxe-config-efi.html

**Comment by jallakim** [comment]
Bruker arch.
