### ISSUE TITLE
Oppetid på SNMP-pollet utstyr i NMS

### ISSUE THREAD

**Issue by ldev** [tech-server/tgmanage#60]
SNMP OID 0.3.6.1.2.1.1.3.0

For oss i tech:net og tech:support hadde det å få den inn på første taben når man trykker på en switch vært ganske sexy :]

**Comment by KristianLyng** [comment]
sysUpTimeInstance er counteren, forsøker å finne ut hvorfor den ikke blir samlet inn nå....

**Comment by KristianLyng** [comment]
Lagt inn nå. Jeg hater SNMP.

Ikke noe kart eller noe på det, og du har foreløpig 100-dels-sekunder, som neppe er å regne som praktisk.

**Comment by KristianLyng** [comment]
@niccofyren kan jo kanskje ekstrahere det siden jeg tror du holder på med div relatert uansett?
