### ISSUE TITLE
NMS: Driftslogg/backlogg

### ISSUE THREAD

**Issue by jallakim** [tech-server/tgmanage#66]
Få på plass *veldig* enkel driftslogg/backlogg som kan vises i NMS-et. Brukes for å logge hendelser som er relevant for påfølgende skift. (typ «distro5 ble slapp, redusert til 2x i VC + 2x uplink mot kant»).

Nice-to-have; flerbrukerstøtte (via BasicAuth mot Wannabe, eller andre ting) slik at man kan merke meldinger som lest eller ei (slik at meldinger forblir om man ikke aktivt merker de som lest).

**Comment by KristianLyng** [comment]
This issue was moved to tech-server/tgnms#20
